name: Run Basic Testes

on:
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      # Clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      # Executar os testes Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
