name: Run Basic Testes - scheduler

on:
  schedule:
  - cron: '* 16 * * 1-5'

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      # Clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      # Executar os testes Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # upload do relatório mocha
      - name: upload relatório 
        uses: actions/upload-artifact@v4
        with:
          name: Relatório
          path: cypress/reports/html
