# Nome da pipeline
name: Run Basic Tests

# Em que momento será executada
on:
  pull_request:
    branches: [main]

jobs:
  # O que vai ser feito nessa pipeline
  cypress-run:
    # Máquina que será usada
    runs-on: ubuntu-latest
    # Passo a passo para rodar os testes
    steps:
      # Clonar o repositório
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3

      # Instalar dependências
      - name: Instalar dependências do projeto
        run: npm install

      # Executar os testes
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
